
CREATE DATABASE NG_GAMES_DB;

USE NG_GAMES_DB;

CREATE TABLE GAMES(
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(180),
    DESCRIPTION VARCHAR(255),
    IMAGE VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE GAMES;